version: '2'
services:
  sql_server:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TestPa$$word123

  mssqlex:
    build: .
    environment:
      - MSSQL_UID=sa
      - MSSQL_PWD=TestPa$$word123
      - MSSQL_HST=tcp:sql_server,1433
    depends_on:
      - sql_server
    command: ["./wait-for-it.sh", "sql_server:1433", "--", "mix", "coverall.travis"]
