version: '2'
services:
  sql_server:
    image: microsoft/mssql-server-linux
    # ports:
    #   - "8989:1433/tcp"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$MSSQL_PWD

  mssqlex:
    build: .
    # ports:
    #   - "8989:1433/tcp"
    environment:
      - MSSQL_UID=$MSSQL_UID
      - MSSQL_PWD=$MSSQL_PWD
      - MSSQL_HST=tcp:sql_server,1433
    depends_on:
      - sql_server
    command: mix test
