version: '2'
services:
  sql_server:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=$MSSQL_PWD

  mssqlex:
    build: .
    environment:
      - MSSQL_UID=$MSSQL_UID
      - MSSQL_PWD=$MSSQL_PWD
      - MSSQL_HST=sql_server
    depends_on:
      - sql_server
    command: mix test
